import {
  Activity,
  Archive,
  BellRing,
  Boxes,
  Cable,
  CalendarClock,
  Cog,
  Container,
  Database,
  DatabaseZap,
  DoorOpen,
  FileKey,
  FileSliders,
  Gauge,
  GitBranch,
  Globe,
  KeyRound,
  type LucideIcon,
  MonitorSmartphone,
  Network,
  Router,
  Rows3,
  Scaling,
  ScrollText,
  Search,
  Server,
  Shield,
  Signpost,
  Split,
  Waypoints,
  Zap,
} from "lucide-react";

export const NODE_KIND_ICONS: Readonly<Record<string, LucideIcon>> = {
  client: MonitorSmartphone,
  cdn: Globe,
  "load-balancer": Split,
  service: Server,
  cache: Zap,
  "sql-database": Database,
  "nosql-database": DatabaseZap,
  queue: Rows3,
  stream: ScrollText,
  worker: Cog,
  "object-storage": Archive,
  "api-gateway": Waypoints,
  "rate-limiter": Gauge,
  "external-api": Cable,
  "search-index": Search,
  scheduler: CalendarClock,
  coordination: KeyRound,
  dns: Signpost,
  ingress: DoorOpen,
  "k8s-service": Network,
  "k8s-deployment": Boxes,
  hpa: Scaling,
  "config-map": FileSliders,
  secret: FileKey,
  alert: BellRing,
  monitoring: Activity,
  "pipeline-stage": GitBranch,
  "artifact-registry": Container,
  "security-group": Shield,
  "nat-gateway": Router,
};

export const FALLBACK_NODE_ICON: LucideIcon = Server;
