import {
  Archive,
  Cable,
  CalendarClock,
  Cog,
  Database,
  DatabaseZap,
  Gauge,
  Globe,
  KeyRound,
  type LucideIcon,
  MonitorSmartphone,
  Rows3,
  ScrollText,
  Search,
  Server,
  Split,
  Waypoints,
  Zap,
} from "lucide-react";

export const NODE_KIND_ICONS: Readonly<Record<string, LucideIcon>> = {
  client: MonitorSmartphone,
  cdn: Globe,
  "load-balancer": Split,
  service: Server,
  cache: Zap,
  "sql-database": Database,
  "nosql-database": DatabaseZap,
  queue: Rows3,
  stream: ScrollText,
  worker: Cog,
  "object-storage": Archive,
  "api-gateway": Waypoints,
  "rate-limiter": Gauge,
  "external-api": Cable,
  "search-index": Search,
  scheduler: CalendarClock,
  coordination: KeyRound,
};

export const FALLBACK_NODE_ICON: LucideIcon = Server;
