export interface OpenApiSchema {
  type?: string | string[];
  format?: string;
  const?: unknown;
  enum?: unknown[];
  items?: OpenApiSchema;
  properties?: Record<string, OpenApiSchema>;
  required?: string[];
  patternProperties?: Record<string, OpenApiSchema>;
  anyOf?: OpenApiSchema[];
  allOf?: OpenApiSchema[];
  additionalProperties?: OpenApiSchema | boolean;
}

export interface OpenApiParameter {
  name: string;
  in: string;
  required?: boolean;
  schema?: OpenApiSchema;
}

export interface Operation {
  summary?: string;
  parameters?: OpenApiParameter[];
  requestBody?: {
    content?: Record<string, { schema?: OpenApiSchema }>;
  };
  responses?: Record<
    string,
    { content?: Record<string, { schema?: OpenApiSchema }> }
  >;
  security?: unknown[];
}

export type PathItem = Record<string, Operation>;

const JSON_CONTENT = "application/json";

const renderSchema = (schema: OpenApiSchema | undefined, depth = 1): string => {
  if (!schema) return "unknown";

  if (schema.const !== undefined) return JSON.stringify(schema.const);

  if (schema.anyOf?.length) {
    return schema.anyOf.map((item) => renderSchema(item, depth)).join(" | ");
  }

  if (schema.allOf?.length) {
    return schema.allOf.map((item) => renderSchema(item, depth)).join(" & ");
  }

  if (schema.enum?.length) {
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (Array.isArray(schema.type)) {
    const members = schema.type.map((type) =>
      renderSchema({ ...schema, type }, depth),
    );
    const nullish = members.filter((member) => member === "null");

    return [...members.filter((member) => member !== "null"), ...nullish].join(
      " | ",
    );
  }

  switch (schema.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `Array<${renderSchema(schema.items, depth)}>`;
    case "object":
      break;
    default:
      return "unknown";
  }

  const entries = Object.entries(schema.properties ?? {});

  if (entries.length === 0) {
    const pattern = Object.values(schema.patternProperties ?? {})[0];

    if (pattern) {
      return `Record<string, ${renderSchema(pattern, depth)}>`;
    }

    const additional = schema.additionalProperties;

    return typeof additional === "object"
      ? `Record<string, ${renderSchema(additional, depth)}>`
      : "Record<string, unknown>";
  }

  const required = new Set(schema.required ?? []);

  const indent = "  ".repeat(depth + 1);

  const members = entries.map(([key, value]) => {
    const optional = required.has(key) ? "" : "?";

    return `${indent}${key}${optional}: ${renderSchema(value, depth + 1)};`;
  });

  return `{\n${members.join("\n")}\n${"  ".repeat(depth)}}`;
};

const successSchema = (operation: Operation): OpenApiSchema | undefined => {
  const responses = operation.responses ?? {};

  for (const [status, response] of Object.entries(responses)) {
    if (!status.startsWith("2")) continue;

    const schema = response.content?.[JSON_CONTENT]?.schema;

    if (schema) return schema;
  }

  return undefined;
};

const EVENT_STREAM_CONTENT = "text/event-stream";

const isEventStream = (operation: Operation): boolean =>
  Object.entries(operation.responses ?? {}).some(
    ([status, response]) =>
      status.startsWith("2") &&
      response.content?.[EVENT_STREAM_CONTENT] !== undefined,
  );

const bodySchema = (operation: Operation): OpenApiSchema | undefined =>
  operation.requestBody?.content?.[JSON_CONTENT]?.schema;

const COERCED_FORMATS = new Set(["integer", "number", "boolean"]);

const isCoercion = (schema: OpenApiSchema): boolean =>
  schema.type === "string" &&
  schema.format !== undefined &&
  COERCED_FORMATS.has(schema.format);

const withoutCoercion = (schema: OpenApiSchema): OpenApiSchema => {
  const members = schema.anyOf?.filter((member) => !isCoercion(member));

  if (!members?.length || members.length === schema.anyOf?.length) {
    return schema;
  }

  return { ...schema, anyOf: members };
};

const querySchema = (
  parameters: OpenApiParameter[] = [],
): OpenApiSchema | undefined => {
  const query = parameters.filter((parameter) => parameter.in === "query");

  if (query.length === 0) return undefined;

  return {
    type: "object",
    properties: Object.fromEntries(
      query.map((parameter) => [
        parameter.name,
        withoutCoercion(parameter.schema ?? {}),
      ]),
    ),
    required: query
      .filter((parameter) => parameter.required)
      .map((parameter) => parameter.name),
  };
};

const HEADER = "// Generated by `bun run generate`. Do not edit.";

const HTTP_METHODS = new Set([
  "get",
  "post",
  "put",
  "patch",
  "delete",
  "head",
  "options",
]);

interface RouteOperation {
  path: string;
  summary?: string;
  body?: OpenApiSchema;
  query?: OpenApiSchema;
  response?: OpenApiSchema;
  auth: boolean;
}

interface RouteNode {
  children: Map<string, RouteNode>;
  operations: Map<string, RouteOperation>;
  param?: string;
  paramType?: string;
}

const createNode = (): RouteNode => ({
  children: new Map(),
  operations: new Map(),
});

const toCamelCase = (segment: string): string =>
  segment.replace(/[-_.]+([a-zA-Z0-9])/g, (_, char: string) =>
    char.toUpperCase(),
  );

const PARAM_PATTERN = /^\{(.+)\}$/;

const insert = (
  root: RouteNode,
  path: string,
  method: string,
  operation: RouteOperation,
  parameters: OpenApiParameter[] = [],
): void => {
  const segments = path.split("/").filter((segment) => segment.length > 0);

  let node = root;

  for (const segment of segments) {
    const param = PARAM_PATTERN.exec(segment)?.[1];
    const key = param ? `:${param}` : toCamelCase(segment);

    let child = node.children.get(key);

    if (!child) {
      child = createNode();
      if (param) child.param = param;
      node.children.set(key, child);
    }

    if (param && child.paramType === undefined) {
      const schema = parameters.find(
        (candidate) => candidate.in === "path" && candidate.name === param,
      )?.schema;

      if (schema?.enum?.length) child.paramType = renderSchema(schema);
    }

    node = child;
  }

  node.operations.set(method, operation);
};

const renderNode = (node: RouteNode, depth: number): string => {
  const indent = "  ".repeat(depth);
  const inner = "  ".repeat(depth + 1);
  const lines: string[] = [];

  for (const [method, operation] of [...node.operations].sort()) {
    const summary = operation.summary
      ? `${inner}/** ${operation.summary} */\n`
      : "";

    const members = [
      `response: ${renderSchema(operation.response, depth + 2)};`,
      operation.body
        ? `body: ${renderSchema(operation.body, depth + 2)};`
        : undefined,
      operation.query
        ? `query: ${renderSchema(operation.query, depth + 2)};`
        : undefined,
      operation.auth ? "auth: true;" : undefined,
    ]
      .filter((member): member is string => member !== undefined)
      .map((member) => `${inner}  ${member}`)
      .join("\n");

    lines.push(`${summary}${inner}${method}: {\n${members}\n${inner}};`);
  }

  for (const [key, child] of [...node.children].sort()) {
    if (child.param) {
      lines.push(
        `${inner}(${child.param}: ${child.paramType ?? "string | number"}): ${renderNode(child, depth + 1)};`,
      );
      continue;
    }

    lines.push(`${inner}${key}: ${renderNode(child, depth + 1)};`);
  }

  return `{\n${lines.join("\n")}\n${indent}}`;
};

const collectPaths = (
  node: RouteNode,
  trail: string[] = [],
  found = new Map<string, string>(),
): Map<string, string> => {
  for (const [method, operation] of node.operations) {
    found.set([...trail, method].join("."), operation.path);
  }

  for (const [key, child] of node.children) {
    collectPaths(child, [...trail, child.param ? ":param" : key], found);
  }

  return found;
};

export const renderRoutes = (paths: Record<string, PathItem>): string => {
  const root = createNode();

  for (const path of Object.keys(paths).sort()) {
    const item = paths[path];

    if (!item) continue;

    for (const method of Object.keys(item).sort()) {
      if (!HTTP_METHODS.has(method)) continue;

      const operation = item[method];

      if (!operation || isEventStream(operation)) continue;

      const body = bodySchema(operation);
      const response = successSchema(operation);

      insert(
        root,
        path,
        method,
        {
          path,
          summary: operation.summary,
          body,
          query: querySchema(operation.parameters),
          response,
          auth: Boolean(operation.security?.length),
        },
        operation.parameters,
      );
    }
  }

  const routePathEntries = collectPaths(root);

  const pathEntries = [...routePathEntries]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `  "${key}": "${value}",`)
    .join("\n");

  return [
    HEADER,
    "",
    `export interface Routes ${renderNode(root, 0)}`,
    "",
    "export const routePaths = {",
    pathEntries,
    "} as const;",
    "",
  ].join("\n");
};
